services:
  web:
    depends_on:
      - redis
      - db
    build: .
    ports:
      - 5000:5000
    environment:
      REDIS_HOST: 'redis'
      DB_HOST: 'db'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'mydatabase'
  redis:
    depends_on:
      - db
    image: redis
    volumes:
      - redis_data:/data
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

volumes:
  redis_data: