name: build and push

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  push_docker:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            abdullahbinahmed/flask-app:latest
            abdullahbinahmed/flask-app:${{ github.sha }}

  linter-checker:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: install python
        run: |
        sudo apt update && sudo apt install python && pip install -r requirements.txt && python test_app.py
